### ISSUE TITLE
Convert gn-tools-pipeline to cronjob

### ISSUE THREAD

**Issue by jeanmi151** [geonetwork/geonetwork-helm-charts#12]
Convert this job https://github.com/geonetwork/geonetwork-helm-charts/blob/2fa3f6e30915998eb133f8ab2f42f525ca7650f8/gn-tools-pipelines/templates/gntoolspipelines-job.yaml
into a cronjob in order to make it easier to trigger it.

**Comment by edevosc2c** [comment]
maybe have it automatically suspended state so that it is not triggered every X time?

**Comment by jeanmi151** [comment]
we can make it run once

**Comment by edevosc2c** [comment]
a cronjob is designed to be run at a specific frequency. you can't run a cronjob once, if you want to run it once it's a job. it's like CRON on linux, you can't run a cron script once.

hence why I proposed to have it in a "suspend: true" state for avoiding it to be run every X time.

**Comment by jeanmi151** [comment]
yeah but a job is boring to trigger
actually, we could make it run automatically once a month

**Comment by edevosc2c** [comment]
ping @f-necas

**Comment by f-necas** [comment]
Not a k8s specialist but we can trigger it once a year ? 

So it gets easiness of cronjob to redeploy and not running everytime. 

The best would be a cronjob which checks if quality score is set, and if it doesn't, runs the pipeline.

**Comment by jeanmi151** [comment]
closing because resolved in here : https://github.com/geonetwork/geonetwork-helm-charts/pull/17
