### ISSUE TITLE
The values.yaml on the datahub chart points to a old image

### ISSUE THREAD

**Issue by fixwhat** [geonetwork/geonetwork-helm-charts#13]
Hello,

I was implementing geonetwork-ui using the Helm charts and realize that the current values.yaml is refering to a 'master' branch. 'Master ' is a very old image and it does not carry the _wc-embedder.html_ file. So the chart works but the advanced web components do not.

I changed from:

```
image:
  repository: geonetwork/geonetwork-ui-datahub
  tag: master
```

to 

```
image:
  repository: geonetwork/geonetwork-ui-datahub
  tag: latest
```

And everything worked.

**Comment by edevosc2c** [comment]
Feel free to send a PR thank you!
