### ISSUE TITLE
wrong url for test-connection

### ISSUE THREAD

**Issue by jeanmi151** [geonetwork/geonetwork-helm-charts#4]
here : https://github.com/geonetwork/geonetwork-helm-charts/blob/main/datahub/templates/tests/test-connection.yaml#L14

when deployed it wget : datahub:80 it should refere to datahub-datahub-svc

**Comment by jeanmi151** [comment]
@edevosc2c  , the following is generated : 
`# Source: datahub/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "datahub-test-connection"
  labels:
    helm.sh/chart: datahub-0.4.1
    app.kubernetes.io/name: datahub
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['datahub:80']
  restartPolicy: Never
`

**Comment by edevosc2c** [comment]
tests removed in https://github.com/geonetwork/geonetwork-helm-charts/commit/5f1e47204bcd1c7c05b6ca6b939805cffd55b4a5
